CREATE TABLE STOREDEVENT
(
    EVENT_ID VARCHAR(36) PRIMARY KEY NOT NULL,
    CHAT_ID BIGINT,
    CREATED TIMESTAMP NOT NULL,
    EVENT_BODY CLOB NOT NULL,
    EVENT_TYPE INT NOT NULL
);
CREATE INDEX CREATED_INDEX ON STOREDEVENT (CREATED);